grails-app/domain/com/travelex/admin/Coupon.groovy
package com.travelex.admin

class Coupon {
    String couponCode
    AmountType amountType = AmountType.AMOUNT
    Status status = Status.ACTIVE
    String amount
    Date dateCreated
    Date lastUpdated
    String validNoOfDays

    static constraints = {


    }
}

grails-app/controllers/com/travelex/admin/CouponController.groovy
package com.travelex.admin

import com.travelex.admin.coupon.CouponVO
import grails.plugins.springsecurity.Secured
import util.AppUtil

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

//@Transactional(readOnly = true)
class CouponController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Coupon.list(params), model: [couponInstanceCount: Coupon.count()]
    }

    def show(Coupon couponInstance) {
        respond couponInstance
    }

    def create() {
        respond new Coupon(params)
    }

    @Transactional
    def save(Coupon couponInstance) {
        CouponVO couponVO = new CouponVO()
        bindData(couponVO, params)
        if (couponVO.validate()) {
            if (couponInstance == null) {
                print('1111111111111111111')
                notFound()
                return
            }

            if (couponInstance.hasErrors()) {
                print('222222222222222222222')
                respond couponInstance.errors, view: 'create'
                return
            }

            couponInstance.save flush: true

            request.withFormat {
                print('3333333333333333333333')

                form {
                    flash.message = message(code: 'default.created.message', args: [message(code: 'couponInstance.label', default: 'Coupon'), couponInstance.id])
                    redirect couponInstance
                }
                '*' { respond couponInstance, [status: CREATED] }
            }
        } else {
            print('in else -------------------')
            render(view: '/coupon/create', model: [couponVO: couponVO])
        }

    }

    def edit(Coupon couponInstance) {
        respond couponInstance
    }

    @Transactional
    def update(Coupon couponInstance) {
        CouponVO couponVO = new CouponVO()
        bindData(couponVO, params)
        if (couponVO.validate()) {
            if (couponInstance == null) {
                notFound()
                return
            }

            if (couponInstance.hasErrors()) {
                respond couponInstance.errors, view: 'edit'
                return
            }

            couponInstance.save flush: true

            request.withFormat {
                form {
                    flash.message = message(code: 'default.updated.message', args: [message(code: 'Coupon.label', default: 'Coupon'), couponInstance.id])
                    redirect couponInstance
                }
                '*' { respond couponInstance, [status: OK] }
            }
        } else {
            print('in else -------------------')
            render(view: '/coupon/edit', model: [couponVO: couponVO,couponInstance:couponInstance ])
        }
    }

    @Transactional
    def delete(Coupon couponInstance) {

        if (couponInstance == null) {
            notFound()
            return
        }

        couponInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Coupon.label', default: 'Coupon'), couponInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'couponInstance.label', default: 'Coupon'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }


    def changeStatusDeactivate() {
        println '=====PARAMS=====' + params
        String couponId = params.couponId
        Coupon coupon = Coupon.findById(couponId as Long)

        coupon.status = Status.EXPIRED

        coupon.save(flush: true)

        redirect(action: "index")

    }

    def changeStatusActivate() {

        println '=====PARAMS=====' + params

        String couponId = params.couponId
        Coupon coupon = Coupon.findById(couponId as Long)

        coupon.status = Status.ACTIVE

        coupon.save(flush: true)

        redirect(action: "index")

    }
}

grails-app/views/coupon/_form.gsp
<%@ page import="com.travelex.admin.Coupon" %>


<table>
    <tr><div class="fieldcontain ${hasErrors(bean: couponInstance, field: 'amount', 'error')} ">
        <td><label for="amount">
            <g:message code="coupon.amount.label" default="Amount"/>

        </label></td><td>
            <g:textField name="amount" value="${couponInstance?.amount}"/>
        </td>
    </div>

        <div class="fieldcontain ${hasErrors(bean: couponInstance, field: 'amountType', 'error')} required">
            <td><label for="amountType">
                <g:message code="coupon.amountType.label" default="Amount Type"/>
                <span class="required-indicator">*</span>
            </label></td><td>
            <g:select name="amountType" from="${com.travelex.admin.AmountType?.values()}"
                      keys="${com.travelex.admin.AmountType.values()*.name()}" required=""
                      value="${couponInstance?.amountType?.name()}"/>
        </td>
        </div>

        <div class="fieldcontain ${hasErrors(bean: couponInstance, field: 'validNoOfDays', 'error')} ">
            <td><label for="validNoOfDays">
                <g:message code="coupon.validNoOfDays.label" default="Valid Days"/>

            </label></td><td>
            <g:textField name="validNoOfDays" value="${couponInstance?.validNoOfDays}"/>
        </td>
        </div>
    </tr>

    <tr><div class="fieldcontain ${hasErrors(bean: couponInstance, field: 'couponCode', 'error')} ">
        <td><label for="couponCode">
            <g:message code="coupon.couponCode.label" default="Coupon Code"/>

        </label></td><td>
            <g:textField name="couponCode" value="${couponInstance?.couponCode}"/>
        </td>
    </div>

        <div class="fieldcontain ${hasErrors(bean: couponInstance, field: 'status', 'error')} required">
            <td><label for="status">
                <g:message code="coupon.status.label" default="Status"/>
                <span class="required-indicator">*</span>
            </label></td><td>
            <g:select name="status" from="${com.travelex.admin.Status?.values()}"
                      keys="${com.travelex.admin.Status.values()*.name()}" required=""
                      value="${couponInstance?.status?.name()}"/>
        </td>
        </div>
    </tr>
</table>

grails-app/views/coupon/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'coupon.label', default: 'Coupon')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span12">
            <div id="tab" class="btn-group">
                <a href="${createLink(controller: 'user', action: 'index')}" id="userId"
                   class="btn btn-large btn-info  disableAll"
                   onclick="activeButton(this.id)">Users</a>
                <a href="${createLink(controller: 'bookingHistory', action: 'index')}" id="hotelId"
                   class="btn btn-large btn-info active disableAll"
                   onclick="activeButton(this.id)">Hotels</a>
                <a href="#Flights" id="flightId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Flights</a>
                <a href="#Activity" id="activityId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Activity</a>
                <a href="#serviceProvider" id="serviceProviderId" class="btn btn-large btn-info disableAll"
                   data-toggle="tab"
                   onclick="activeButton(this.id)">Service Provider</a>

            </div>


            <div class="tab-content" style="margin-top: 1%">

                <div class="tab-pane active" id="Hotels">

                    <ul class="nav nav-tabs">
                        <li><a
                                href="${createLink(controller: 'coupon', action: 'index')}">Coupon List</a></li>
                        <li class="active"><a
                                href="${createLink(controller: 'coupon', action: 'create')}">New Coupon</a></li>
                    </ul>

                    <div class="tab-content" style="margin-top: 1%">
                        <div class="tab-pane active">
                            <div class="col-md-12">
                                <div id="create-coupon" class="content scaffold-create" role="main">
                                    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
                                    <g:if test="${flash.message}">
                                        <div class="message" role="status">${flash.message}</div>
                                    </g:if>
                                    <g:hasErrors bean="${couponVO}">
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert"><span
                                                    aria-hidden="true">&times;
                                            </span><span class="sr-only">Close</span></button>

                                            <div id="errors" class="alert alert-error">
                                                <g:renderErrors bean="${couponVO}"/>
                                            </div>
                                        </div>
                                    </g:hasErrors>
                                    <g:form url="[resource: couponInstance, action: 'save']">
                                        <fieldset class="form">
                                            <g:render template="form"/>
                                        </fieldset>
                                        <fieldset class="buttons">
                                            <g:submitButton name="create" class="save btn btn-success"
                                                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
                                        </fieldset>
                                    </g:form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

grails-app/views/coupon/edit.gsp
<%@ page import="com.travelex.admin.Coupon" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span12">
            <div id="tab" class="btn-group">
                <a href="${createLink(controller: 'user', action: 'index')}" id="userId"
                   class="btn btn-large btn-info  disableAll"
                   onclick="activeButton(this.id)">Users</a>
                <a href="${createLink(controller: 'bookingHistory', action: 'index')}" id="hotelId"
                   class="btn btn-large btn-info active disableAll"
                   onclick="activeButton(this.id)">Hotels</a>
                <a href="#Flights" id="flightId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Flights</a>
                <a href="#Activity" id="activityId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Activity</a>
                <a href="#serviceProvider" id="serviceProviderId" class="btn btn-large btn-info disableAll"
                   data-toggle="tab"
                   onclick="activeButton(this.id)">Service Provider</a>

            </div>

            <div class="tab-content" style="margin-top: 1%">

                <div class="tab-pane active" id="Hotels">

                    <ul class="nav nav-tabs">
                        <li><a
                                href="${createLink(controller: 'coupon', action: 'index')}">Coupon List</a></li>
                        <li><a
                                href="${createLink(controller: 'coupon', action: 'create')}">New Coupon</a></li>
                        <li class="active"><a
                                href="${createLink(controller: 'coupon', action: 'edit', params: [couponInstance: couponInstance?.id])}">Edit Coupon</a>
                        </li>
                    </ul>

                    <div class="tab-content" style="margin-top: 1%">
                        <div class="tab-pane active">
                            <div class="col-md-12">
                                <div id="edit-coupon" class="content scaffold-edit" role="main">
                                    <g:hasErrors bean="${couponVO}">
                                        <div class="alert alert-danger alert-dismissible" role="alert">
                                            <button type="button" class="close" data-dismiss="alert"><span
                                                    aria-hidden="true">&times;
                                            </span><span class="sr-only">Close</span></button>

                                            <div id="errors" class="alert alert-error">
                                                <g:renderErrors bean="${couponVO}"></g:renderErrors>
                                            </div>
                                        </div>
                                    </g:hasErrors>
                                    <g:form url="[resource: couponInstance, action: 'update']" method="PUT">
                                        <g:hiddenField name="version" value="${couponInstance?.version}"/>
                                        <fieldset class="form">
                                            <g:render template="form"/>
                                        </fieldset>
                                        <fieldset class="buttons">
                                            <g:actionSubmit class="save btn btn-success" action="update"
                                                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
                                        </fieldset>
                                    </g:form>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

grails-app/views/coupon/index.gsp
<%@ page import="com.travelex.admin.Status; com.travelex.admin.Coupon" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span12">
            <div id="tab" class="btn-group">
                <a href="${createLink(controller: 'user', action: 'index')}" id="userId"
                   class="btn btn-large btn-info  disableAll"
                   onclick="activeButton(this.id)">Users</a>
                <a href="${createLink(controller: 'bookingHistory', action: 'index')}" id="hotelId"
                   class="btn btn-large btn-info active disableAll"
                   onclick="activeButton(this.id)">Hotels</a>
                <a href="#Flights" id="flightId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Flights</a>
                <a href="#Activity" id="activityId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Activity</a>
                <a href="#serviceProvider" id="serviceProviderId" class="btn btn-large btn-info disableAll"
                   data-toggle="tab"
                   onclick="activeButton(this.id)">Service Provider</a>

            </div>


            <div class="tab-content" style="margin-top: 1%">

                <div class="tab-pane active" id="Hotels">

                    <ul class="nav nav-tabs">
                        <li><a
                                href="${createLink(controller: 'bookingHistory', action: 'index')}">Booking List</a>
                        </li>
                        <li class="active"><a
                                href="${createLink(controller: 'coupon', action: 'index')}">Coupon List</a></li>
                        <li><a href="${createLink(controller: 'paymentInfo', action: 'index')}">Payment List</a></li>
                        <li><a href="${createLink(controller: 'setMargin', action: 'index')}">Margin List</a></li>
                    </ul>

                    <div class="tab-content" style="margin-top: 1%">
                        <div class="tab-pane active">
                            <p class="pull-right"><a class="btn btn-primary"
                                                     href="${createLink(controller: 'coupon', action: 'create')}">Create Coupon</a>
                            </p>
                            <table class="table table-bordered table-condensed">
                                <thead>
                                <tr>
                                    <th class="text-center">#</th>
                                    <th class="text-center">Coupon Code</th>
                                    <th class="text-center">Amount</th>
                                    <th class="text-center">Amount Type</th>
                                    <th class="text-center">Status</th>
                                    <th class="text-center">Valid No Of Days</th>
                                    <th class="text-center">Action</th>

                                </tr>
                                </thead>
                                <tbody>
                                <g:each in="${couponInstanceList}" status="i" var="couponInstance">
                                    <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
                                        <td class="text-center">${fieldValue(bean: couponInstance, field: 'id')}</td>
                                        <td class="text-center">${fieldValue(bean: couponInstance, field: "couponCode")}</td>


                                        <td class="text-center"><g:link action="show"
                                                                        id="${couponInstance.id}">${fieldValue(bean: couponInstance, field: "amount")}</g:link></td>

                                        <td class="text-center">${fieldValue(bean: couponInstance, field: "amountType")}</td>


                                        <td class="text-center">${fieldValue(bean: couponInstance, field: "status")}</td>
                                        <td class="text-center">${fieldValue(bean: couponInstance, field: "validNoOfDays")}</td>

                                        <g:if test="${couponInstance?.status == Status.ACTIVE}">
                                            <td class="text-center"><a
                                                    href="${createLink(controller: "coupon", action: "changeStatusDeactivate", params: [couponId: couponInstance?.id])}"
                                                    class="btn btn-success">Deactivate</a></td>
                                        </g:if>
                                        <g:else>
                                            <td class="text-center"><a
                                                    href="${createLink(controller: "coupon", action: "changeStatusActivate", params: [couponId: couponInstance?.id])}"
                                                    class="btn btn-danger">Activate</a></td>
                                        </g:else>
                                    </tr>
                                </g:each>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

grails-app/views/coupon/show.gsp
<%@ page import="com.travelex.admin.Coupon" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="span12">
            <div id="tab" class="btn-group">
                <a href="${createLink(controller: 'user', action: 'index')}" id="userId"
                   class="btn btn-large btn-info  disableAll"
                   onclick="activeButton(this.id)">Users</a>
                <a href="${createLink(controller: 'bookingHistory', action: 'index')}" id="hotelId"
                   class="btn btn-large btn-info active disableAll"
                   onclick="activeButton(this.id)">Hotels</a>
                <a href="#Flights" id="flightId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Flights</a>
                <a href="#Activity" id="activityId" class="btn btn-large btn-info disableAll" data-toggle="tab"
                   onclick="activeButton(this.id)">Activity</a>
                <a href="#serviceProvider" id="serviceProviderId" class="btn btn-large btn-info disableAll"
                   data-toggle="tab"
                   onclick="activeButton(this.id)">Service Provider</a>

            </div>

            <div class="tab-content" style="margin-top: 1%">

                <div class="tab-pane active" id="Hotels">

                    <ul class="nav nav-tabs">
                        <li><a
                                href="${createLink(controller: 'coupon', action: 'index')}">Coupon List</a></li>
                        <li><a
                                href="${createLink(controller: 'coupon', action: 'create')}">New Coupon</a></li>
                        <li class="active"><a
                                href="${createLink(controller: 'coupon', action: 'edit', params: [couponInstance: couponInstance?.id])}">Edit Coupon</a>
                        </li>
                    </ul>

                    <div class="tab-content" style="margin-top: 1%">
                        <div class="tab-pane active">
                            <div class="col-md-9">

                                <div id="show-coupon" class="content scaffold-show" role="main">
                                    <table class="table table-bordered table-condensed">
                                        <thead>
                                        <th>Amount</th>
                                        <th>Amount Type</th>
                                        <th>Coupon Code</th>
                                        <th>Valid No. Of Day</th>
                                        <th>Status</th>
                                        </thead>
                                        <tbody>
                                        <tr>
                                            <td>${couponInstance?.amount}</td>
                                            <td>${couponInstance?.amountType}</td>
                                            <td>${couponInstance?.couponCode}</td>
                                            <td>${couponInstance?.validNoOfDays}</td>
                                            <td>${couponInstance?.status}</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <g:form url="[resource: couponInstance, action: 'delete']" method="DELETE">
                                        <fieldset class="buttons">
                                            <g:link class="edit btn btn-success" action="edit"
                                                    resource="${couponInstance}"><g:message
                                                    code="default.button.edit.label" default="Edit"/></g:link>
                                            <g:actionSubmit class="delete btn btn-primary" action="delete"
                                                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                                                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
                                        </fieldset>
                                    </g:form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>