grails-app/domain/com/travelex/Hotel/City.groovy
package com.travelex.Hotel

class City {

    String locationId
    String parentId
    Date dateCreated
    Date lastUpdated
    String countryCode
    String name

    static hasMany = [locality: AllLocalityForLocation]

    static constraints = {
        name(nullable: false)
    }

    City() {

    }

    City(def locationData) {
        this.locationId = locationData.attribute("id")
        this.parentId = locationData.attribute("parent_id")
        this.countryCode = locationData.attribute("countryCode")
        this.name = locationData.name.text()
    }
}

grails-app/domain/com/travelex/Hotel/Hotel.groovy
package com.travelex.Hotel

import com.travelex.admin.PackageHotelType
import com.travelex.common.Address
import com.travelex.common.Facility
import com.travelex.socials.Enums.HotelType

class Hotel {

    String name
    String summary
    String contactNo
    String website
    String mainImageName
    String mainImageType
    HotelType type = HotelType.RESORTS_AND_PLACES
    PackageHotelType packageHotelType = PackageHotelType.THREESTAR
    List<Facility> hotelFacilities = []
    List<HotelRoom> hotelRooms = []
    List<HotelPicture> hotelPictures = []
    Date dateCreated
    Date lastUpdated


    static transients = ['getPictureUrl', 'getCity']
    static hasMany = [hotelPictures: HotelPicture, hotelRooms: HotelRoom]
//    ServiceProvider serviceProvider

    static constraints = {
        name(nullable: false, blank: false)
        summary(nullable: false, blank: false)
        contactNo(nullable: true, blank: true)
        website(nullable: true, blank: true)
        mainImageName(nullable: true, blank: true)
        mainImageType(nullable: true, blank: true)
        type(nullable: false)
        packageHotelType(nullable: false)
    }

    static mapping = {
        summary type: 'text'
    }

    public Facility getFacility() {
        return hotelFacilities.first()
    }

//    public HotelRoom getRoomTypes(){
//        return roomTypes.maxPrice
//    }

//    public Address getCity() {
//        return address.city
//    }

}

grails-app/views/hotelTemplates/_hotelRating.gsp
<g:if test="${(hotelInstance?.hotelRating == "OneStar" || "TwoStar" || "ThreeStar" || "FourStar" || "FiveStar" || "SixStar" || "SevenStar")}">
    <g:if test="${hotelInstance?.hotelRating == 'OneStar' || hotelInstance?.hotelRating == '1'}">
        <g:each in="${1..1}" var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:if>
    <g:elseif
            test="${hotelInstance?.hotelRating == 'TwoStar' || hotelInstance?.hotelRating == '2'}">
        <g:each in="${1..2}" var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:elseif>
    <g:elseif
            test="${hotelInstance?.hotelRating == 'ThreeStar' || hotelInstance?.hotelRating == '3'}">
        <g:each in="${1..3}" var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:elseif>
    <g:elseif
            test="${hotelInstance?.hotelRating == 'FourStar' || hotelInstance?.hotelRating == '4'}">
        <g:each in="${1..4}"
                var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:elseif>

    <g:elseif
            test="${hotelInstance?.hotelRating == 'FiveStar' || hotelInstance?.hotelRating == '5'}">
        <g:each in="${1..5}" var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:elseif>
    <g:elseif
            test="${hotelInstance?.hotelRating == 'SixStar' || hotelInstance?.hotelRating == '6'}">
        <g:each in="${1..6}" var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:elseif>
    <g:elseif
            test="${hotelInstance?.hotelRating == 'SevenStar' || hotelInstance?.hotelRating == '7'}">
        <g:each in="${1..7}" var="a"><img
                src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
    </g:elseif>
</g:if>

<g:elseif
        test="${(hotelInstance?.hotelRating == "0" || "1" || "2" || "3" || "4" || "5" || "6" || "7")}">
    <g:each
            in="${1..(hotelInstance?.hotelRating as Integer)}"
            var="a"><img
            src="${resource(dir: '/images', file: 'star1.png')}"></g:each>
</g:elseif>
<g:else>
    ${hotelInstance?.hotelRating}
</g:else>

grails-app/views/hotelTemplates/_invoiceTemplate.gsp
<%@ page import="java.math.RoundingMode; com.travelex.booking.Adult" %>
<br>

<div class="row" style="margin-bottom: 100px">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <img class="panel-title text-left" src="${resource(dir: '/images/appimages', file: 'appLogo.png')}"
                 height="35">

            <h4 class="panel-title text-center" style="margin-top: -15px"><strong>Invoice Detail</strong></h4>

            <h4 class="panel-title text-right" style="margin-top: -15px"><a href=""
                                                                            onclick="window.print()">Print Invoice</a>
            </h4>

        </div>

        <div class="panel-body">
            <div class="row">

                <div class="col-md-4">
                    <addresss>
                        <strong>Travelex 360 Pvt.Ltd.</strong>
                        <br>
                        25/60,&nbsp;A block,
                        <br>
                        Middle circle, Connaught Place
                        <br>
                        New Delhi,110001
                    </addresss>
                </div>

                <div class="col-md-4">
                    <address>
                        <strong>To:-</strong>
                        <br>
                        <g:each in="${Adult.findAllByRoomBooked(roomBookedList.first())}" var="adult">
                            <g:if test="${adult.laedPassanger}">
                                ${adult.adultFirstName}&nbsp;&nbsp;${adult.adultLastName}
                            </g:if>
                        </g:each>
                        <br>
                        <strong>Nationality&nbsp;&nbsp;&nbsp;${bookingHistory?.counrtyName}</strong>
                    </address>
                </div>

                <div class="col-md-4">
                    <p><strong>Check-In</strong>&nbsp;&nbsp;${bookingHistory?.checkIn?.format('dd/MM/yyyy')}</p>

                    <p><strong>Check-Out</strong>&nbsp;&nbsp;${bookingHistory?.checkOut?.format('dd/MM/yyyy')}</p>

                </div>
            </div>
            <br>
            <table class="table table-bordered table-condensed">
                <tr>
                    <td class="text-center">Hotel Name</td>
                    <td class="text-center">Room Type</td>
                    <td class="text-center">Pax Name</td>
                    <td class="text-center">Room(s)</td>
                    <td class="text-center">Night(s)</td>
                    <td class="text-center">Rate</td>
                    <td class="text-center">Tax</td>
                    <td class="text-center">Total</td>
                </tr>
                <g:each in="${roomBookedList}" var="roomBooked">
                    <tr>
                        <td class="text-center">${hotelForBooking?.hotelName}</td>
                        <td class="text-center">${roomBooked?.roomCategory}</td>
                        <td class="text-center">${roomBooked?.adults?.first()?.adultFirstName}&nbsp;${roomBooked?.adults?.first()?.adultLastName}</td>
                        <td class="text-center">${1}</td>
                        <td class="text-center">${bookingHistory?.checkOut - bookingHistory?.checkIn}</td>
                        <td class="text-center">${paymentInfo?.amount}</td>
                        <td class="text-center">${paymentInfo?.totalTax?.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP)}</td>
                        <td class="text-center">${paymentInfo?.amount?.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP) + paymentInfo?.totalTax?.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP)}</td>
                    </tr>
                </g:each>
                <tr>
                    <td class="text-center" colspan="6">Payment Gateway Service Charge</td>
                    <td colspan="6">${paymentInfo?.payUMoneyStake}</td>
                </tr>
                <tr>
                    <td class="text-center" colspan="6">Total</td>
                    <td colspan="6">${((paymentInfo.amount.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP) * (bookingHistory?.noOfRooms?.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP))) + (paymentInfo.totalTax.toBigDecimal()?.setScale(2, RoundingMode.HALF_UP) * (bookingHistory?.noOfRooms?.toBigDecimal()))) + paymentInfo.payUMoneyStake.toBigDecimal()}</td>
                </tr>

            </table>
            <tr><strong style="color: blue">Remarks</strong></tr>

            <p>
                Please note that while your booking had been confirmed and is guaranteed, the rooming list with your name may not be adjusted in the hotel's reservation system until closer to arrival.
            </p>
            <tr><strong style="color: blue">Booking Terms & Conditions:</strong></tr>

            <p>
                You must present a photo ID at the time of check in. Hotel may ask for credit card or cash deposit for the extra services at the time of check in.

                All extra charges should be collected directly from clients prior to departure such as parking, phone calls, room service, city tax, etc.

                We don’t accept any responsibility for additional expenses due to the changes or delays in air, road, rail, sea or indeed of any other causes, all such expenses will have to be borne by passengers.

                In case of wrong residency & nationality selected by user at the time of booking; the supplement charges may be applicable and need to be paid to the hotel by guest on check in/ check out.
            </p>
        </div>
    </div>
</div>

grails-app/views/hotelTemplates/_mailHotelVoucherTemplate.gsp
<%@ page import="com.travelex.booking.RoomBooked; com.travelex.booking.Adult; com.travelex.booking.Child" %>
<%@ page contentType="text/html;charset=UTF-8" %>

<div class="row" style="margin-top: 20px">
    <table class="table table-bordered table-stripped table-condensed">
        <tr style="background-color: #dcdcdc;height: 50px">
            <td colspan="4" class="text-left"><img src="../images/appimages/appLogo.png" height="40"/></td>
            <td colspan="4" class="text-center"><h4>Hotel Voucher</h4></td>
        </tr>
        <tr>
            <td colspan="4" class="text-center"><strong>Booking Id</strong></td>
            <td colspan="4" class="text-center"><strong>Confirmation No</strong></td>
            <td colspan="4" class="text-center"><strong>Reference No</strong></td>
        </tr>
        <tr>
            <td colspan="4" class="text-center">${bookingHistory?.bookingIdTrvlx}</td>
            <td colspan="4" class="text-center">${bookingHistory?.confirmationIdTrvlx}</td>
            <td colspan="4" class="text-center">${bookingHistory?.bookId}</td>
        </tr>
        <tr>
            <td colspan="4"><strong
                    class="pull-left">Hotel Address:-</strong><strong
                    class="pull-right">${hotelForBooking?.hotelAddress}</strong></td>
            <td colspan="4"><strong class="pull-left">Hotel Name:-</strong><strong
                    class="pull-right">${hotelForBooking?.hotelName}</strong></td>
            <td colspan="4"
                class="text-center"><strong class="pull-left">Last Cancellation Date:-</strong><strong
                    class="pull-right">${RoomBooked.findByHotelForBooking(hotelForBooking)?.lastCancellationDate?.format('dd/MM/yyyyy')}</strong>
            </td>
        </tr>
    </table>
    <table class="table table-bordered" style="margin-top: -15px">
        <tr style="background-color: #dcdcdc;height: 30px">
            <td colspan="4" class="text-center"><strong>Room Type</strong></td>
            <td colspan="4" class="text-center"><strong>No. Of Guest</strong></td>
            <td colspan="4" class="text-center"><strong>Guest Name</strong></td>
        </tr>
        <g:each in="${roomBookedList}" var="roomBooked">
            <tr>
                <td colspan="4" class="text-center">${roomBooked?.roomCategory}</td>
                <td colspan="4"
                    class="text-center">${(Adult.findAllByRoomBooked(roomBooked).size() + Child.findAllByRoomBooked(roomBooked).size())}</td>
                <td colspan="4"
                    class="text-center">
                    <p><strong class="pull-left">Adult(s)</strong><i
                            class="pull-right">${Adult.findAllByRoomBooked(roomBooked).adultFirstName.join(',')}</i></p>
                    <br>

                    <p><strong class="pull-left">Child(s)</strong><i
                            class="pull-right">${Child.findAllByRoomBooked(roomBooked).childFirstName.join(',')}</i></p>
                </td>
            </tr>
        </g:each>
    </table>
    <table class="table table-bordered">
        <tr>
            <th>No. Of Night(s)</th>
            <td colspan="4">${bookingHistory?.checkOut - bookingHistory?.checkIn}</td>
            <th>No. Of Room(s)</th>
            <td colspan="4">${bookingHistory?.noOfRooms}</td>
            <th>Email</th>
            <td colspan="4">${bookingHistory?.user?.username}</td>
        </tr>
        <tr>
            <th>Check In</th>
            <td colspan="4">${bookingHistory?.checkIn?.format('dd/MM/yyyy')}</td>
            <th>Check Out</th>
            <td colspan="4">${bookingHistory?.checkOut?.format('dd/MM/yyyy')}</td>
            <th>Contact Info</th>
            <td colspan="4">${bookingHistory?.user?.mobNo}</td>
        </tr>
        <tr>
            <td colspan="12"><p><strong class="pul-left" style="color: dodgerblue">Cancellation Policy:</strong></p>

                <p>${hotelForBooking?.roomBooked?.cancelPolicy?.first()}</p>
            </td>
        </tr>
        <tr>
            <td colspan="12"><p><strong class="pul-left" style="color: dodgerblue">Remarks:</strong></p>

                <p>Please note that while your booking had been confirmed and is guaranteed, the rooming list with your name may not be adjusted in the hotel's reservation system until closer to arrival.
                </p>
            </td>
        </tr>


        <tr>
            <td colspan="12"><p><strong class="pul-left"
                                        style="color: dodgerblue">Booking Terms & Conditions:</strong></p>

                <p>You must present a photo ID at the time of check in. Hotel may ask for credit card or cash deposit for the extra services at the time of check in.</p>

                <p>All extra charges should be collected directly from clients prior to departure such as parking, phone calls, room service, city tax, etc.</p>

                <p>We don’t accept any responsibility for additional expenses due to the changes or delays in air, road, rail, sea or indeed of any other causes, all such expenses will have to be borne by passengers.</p>

                <p>In case of wrong residency & nationality selected by user at the time of booking; the supplement charges may be applicable and need to be paid to the hotel by guest on check in/ check out.</p>

                <p>Any special request for bed type, early check in, late check out, smoking rooms, etc are not guaranteed as subject to availability at the time of check in.</p>
            </td>
        </tr>
    </table>
</div>

grails-app/views/hotelTemplates/_selectCity.gsp
<script type="text/javascript">
    var config = {
        '.chosen-select': {},
        '.chosen-select-deselect': {allow_single_deselect: true},
        '.chosen-select-no-single': {disable_search_threshold: 10},
        '.chosen-select-no-results': {no_results_text: 'Oops, nothing found!'},
        '.chosen-select-width': {width: "95%"}
    }
    for (var selector in config) {
        $(selector).chosen(config[selector]);
    }
</script>
<g:select name="place" from="${citiesList}" optionKey="id" optionValue="name" onkeyup="findCity()"
          class="chosen-select form-control" value="${cityId}"
          noSelection="${['': 'Select Location....']}"/>

%{--<input type="text" class="form-control" value="${cityList?.name}" id="selectCity" name="place" onkeyup="findCity()">--}%


%{--<script>--}%
    %{--function findCity() {--}%
        %{--var tempCity = $("#selectCity").val();--}%
        %{--alert(tempCity);--}%
        %{--$.ajax({--}%
            %{--url: "${createLink(controller: 'hotelService',action: 'findCityForHotel')}",--}%
            %{--type: "POST",--}%
            %{--data: {place: tempCity},--}%
            %{--success: function (data) {--}%
                %{--alert(data);--}%
                %{--$("#selectCity").html(data);--}%
            %{--}--}%
        %{--});--}%
    %{--}--}%
%{--</script>--}%

grails-app/views/hotelTemplates/_userHotelBookingTemplate.gsp
<%@ page import="com.travelex.booking.HotelForBooking" %>
<table class="table table-bordered table-stripped">
    <tr>
        <th>Book Reference No</th>
        <th>Room Category</th>
        <th>No of rooms booked</th>
        <th>Checked In</th>
        <th>Checked Out</th>
        <th>Action</th>
    </tr>

    <g:each in="${bookingHistoryList}" var="booking">

        <tr>
            <td>${booking?.bookId}</td>

            <td>${HotelForBooking.findByBookingHistory(booking)?.roomBooked?.roomCategory?.first()}</td>

            <td>${booking?.noOfRooms}</td>

            <td>${booking?.checkIn?.format('dd/MM/yyyy')}</td>
            <td>${booking?.checkOut?.format('dd/MM/yyyy')}</td>
            <td><g:if test="${!booking?.bookingCancelId}">
                <a href="${createLink(controller: "home", action: "cancelRoomBooking", params: [bookRefNo: booking?.bookId, bookingHistoryId: booking?.id])}"
                   class="btn btn-xs btn-primary pull-right ui-popover" data-toggle="tooltip"
                   data-placement="top"
                   title="Cancel Booking">
                    Cancel Booking
                </a>
            </g:if>
                <g:else>
                    <a href="#" class="btn btn-xs btn-danger disabled">Cancelled</a>
                </g:else>

                <a href="${createLink(controller: 'home', action: 'showVoucher', params: [bookingHistoryId: booking?.id])}"
                   class="btn btn-xs btn-primary">View Voucher</a>
                <a href="${createLink(controller: 'home', action: 'showInvoice', params: [bookingHistoryId: booking?.id])}"
                   class="btn btn-xs btn-primary">View Invoice</a>
            </td>
        </tr>
    </g:each>
</table>

grails-app/views/hotelTemplates/_voucherTemplate.gsp
<%@ page import="com.travelex.booking.RoomBooked; com.travelex.booking.Adult; com.travelex.booking.Child" %>
<br>

<div class="row" style="margin-top: 20px">
    <table class="table table-bordered table-stripped table-condensed">
        <tr style="background-color: #dcdcdc;height: 50px">
            <td colspan="4" class="text-left"><img src="../images/appimages/appLogo.png" height="40"/></td>
            <td colspan="4" class="text-center"><h4>Hotel Voucher</h4></td>
            <td colspan="4" class="text-right"><b><a data-toggle="modal" data-target="#sendVoucher"
                                                     href="">Email /</a><a onclick="window.print()"
                                                                           href="">Print Voucher</a></b></td>
        </tr>
        <tr>
            <td colspan="4" class="text-center"><strong>Booking Id</strong></td>
            <td colspan="4" class="text-center"><strong>Confirmation No</strong></td>
            <td colspan="4" class="text-center"><strong>Reference No</strong></td>
        </tr>
        <tr>
            <td colspan="4" class="text-center">${bookingHistory?.bookingIdTrvlx}</td>
            <td colspan="4" class="text-center">${bookingHistory?.confirmationIdTrvlx}</td>
            <td colspan="4" class="text-center">${bookingHistory?.bookId}</td>
        </tr>
        <tr>
            <td colspan="4"><strong
                    class="pull-left">Hotel Address:-</strong><strong
                    class="pull-right">${hotelForBooking?.hotelAddress}</strong></td>
            <td colspan="4"><strong class="pull-left">Hotel Name:-</strong><strong
                    class="pull-right">${hotelForBooking?.hotelName}</strong></td>
            <td colspan="4"
                class="text-center"><strong class="pull-left">Last Cancellation Date:-</strong><strong
                    class="pull-right">${RoomBooked.findByHotelForBooking(hotelForBooking)?.lastCancellationDate?.format('dd/MM/yyyyy')}</strong>
            </td>
        </tr>
    </table>
    <table class="table table-bordered" style="margin-top: -15px">
        <tr style="background-color: #dcdcdc;height: 30px">
            <td colspan="4" class="text-center"><strong>Room Type</strong></td>
            <td colspan="4" class="text-center"><strong>No. Of Guest</strong></td>
            <td colspan="4" class="text-center"><strong>Guest Name</strong></td>
        </tr>
        <g:each in="${roomBookedList}" var="roomBooked">
            <tr>
                <td colspan="4" class="text-center">${roomBooked?.roomCategory}</td>
                <td colspan="4"
                    class="text-center">${(Adult.findAllByRoomBooked(roomBooked).size() + Child.findAllByRoomBooked(roomBooked).size())}</td>
                <td colspan="4"
                    class="text-center">
                    <p><strong class="pull-left">Adult(s)</strong><i
                            class="pull-right">${Adult.findAllByRoomBooked(roomBooked).adultFirstName.join(',')}</i></p>
                    <br>

                    <p><strong class="pull-left">Child(s)</strong><i
                            class="pull-right">${Child.findAllByRoomBooked(roomBooked).childFirstName.join(',')}</i></p>
                </td>
            </tr>
        </g:each>
        <tr>
            <td colspan="4"></td>
            <td colspan="4"></td>
            <td colspan="4" class="text-center"><p><strong class="pull-left">Nationality</strong><i
                    class="pull-right">${bookingHistory?.counrtyName}</i></p>
            </td>
        </tr>
    </table>
    <table class="table table-bordered">
        <tr>
            <th>No. Of Night(s)</th>
            <td colspan="4">${bookingHistory?.checkOut - bookingHistory?.checkIn}</td>
            <th>No. Of Room(s)</th>
            <td colspan="4">${bookingHistory?.noOfRooms}</td>
            <th>Email</th>
            <td colspan="4">${bookingHistory?.user?.username}</td>
        </tr>
        <tr>
            <th>Check In</th>
            <td colspan="4">${bookingHistory?.checkIn?.format('dd/MM/yyyy')}</td>
            <th>Check Out</th>
            <td colspan="4">${bookingHistory?.checkOut?.format('dd/MM/yyyy')}</td>
            <th>Contact Info</th>
            <td colspan="4">${bookingHistory?.user?.mobNo}</td>
        </tr>


        <tr>
            <th>Booking Status</th>
            <td colspan="4">${bookingHistory?.bookingStatus}</td>
        </tr>

        <tr>
            <td colspan="12"><p><strong class="pul-left" style="color: dodgerblue">Cancellation Policy:</strong></p>

                <p>${hotelForBooking?.roomBooked?.cancelPolicy?.first()}</p>
            </td>
        </tr>
        <tr>
            <td colspan="12"><p><strong class="pul-left" style="color: dodgerblue">Remarks:</strong></p>

                <p>Please note that while your booking had been confirmed and is guaranteed, the rooming list with your name may not be adjusted in the hotel's reservation system until closer to arrival.
                </p>
            </td>
        </tr>


        <tr>
            <td colspan="12"><p><strong class="pul-left"
                                        style="color: dodgerblue">Booking Terms & Conditions:</strong></p>

                <p>You must present a photo ID at the time of check in. Hotel may ask for credit card or cash deposit for the extra services at the time of check in.</p>

                <p>All extra charges should be collected directly from clients prior to departure such as parking, phone calls, room service, city tax, etc.</p>

                <p>We don’t accept any responsibility for additional expenses due to the changes or delays in air, road, rail, sea or indeed of any other causes, all such expenses will have to be borne by passengers.</p>

                <p>In case of wrong residency & nationality selected by user at the time of booking; the supplement charges may be applicable and need to be paid to the hotel by guest on check in/ check out.</p>

                <p>Any special request for bed type, early check in, late check out, smoking rooms, etc are not guaranteed as subject to availability at the time of check in.</p>
            </td>
        </tr>
    </table>
</div>

<div class="modal fade" id="sendVoucher" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span
                        class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Send Voucher</h4>
            </div>

            <div class="modal-body">
                <div class="container">
                    <g:form controller="home" action="sendVoucherAsEmail">
                        <div class="row">
                            %{--<div class="col-md-4">--}%
                            %{--<label><strong style="float: right">UserName<travelx:star/></strong></label>--}%
                            %{--</div>--}%

                            <div class="col-md-8 form-group input-group">
                                <input type="email" class="form-control" name="emailTO"
                                       value="${bookingHistory?.user?.username}" readonly/>
                                <span class="input-group-addon">
                                    <travelx:star/>
                                </span>
                            </div>

                            <div class="col-md-4">
                                <input type="submit" class="btn btn-primary" value="Send"/>
                            </div>

                        </div>
                        <g:hiddenField name="bookingHistoryId" value="${bookingHistory?.id}"/>
                    </g:form>
                </div>
            </div>

            <div class="modal-footer">
                %{--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>--}%
                %{--<button type="button" class="btn btn-primary">Send</button>--}%
            </div>
        </div>
    </div>
</div>

grails-app/views/hotelTemplates/technicalProblem.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
    <meta name="layout" content="mainForLanding"/>
</head>

<body>
<div class="container">

<strong>Please try again ! We are feeling some technical issue.</strong>

</div>
</body>
</html>