grails-app/domain/com/travelex/User/PaymentInfo.groovy
package com.travelex.User

import com.travelex.Hotel.BookingHistory

class PaymentInfo {

    Date dateCreated
    Date lastUpdated
    String payuMoneyId
    String paymentMode
    String paymentStatus
    String merchantKey
    String paymentTxnId
    String amount
    String totalTax
    String payUMoneyStake
    String discount
    String fName
    String email
    String userCardNumber
    String mihpayid
    String productinfo
    BookingHistory bookingHistory


    static constraints = {
        payuMoneyId(nullable: false, blank: false)
        paymentMode(nullable: false, blank: false)
        paymentStatus(nullable: false, blank: false)
        merchantKey(nullable: false, blank: false)
        paymentTxnId(nullable: false, blank: false)
        amount(nullable: false, blank: false)
        totalTax(nullable: false, blank: false)
        discount(nullable: false, blank: false)
        fName(nullable: false, blank: false)
        email(nullable: false, blank: false)
        userCardNumber(nullable: false, blank: false)
        mihpayid(nullable: false, blank: false)
        productinfo(nullable: false, blank: false)
        bookingHistory(nullable: false)
        payUMoneyStake(nullable: false, blank: false)
    }

    void savePaymentInfoFromPayUMoney(Map map) {
        this.payuMoneyId = map.payuMoneyId
        this.paymentMode = map.mode
        this.paymentStatus = map.status
        this.paymentTxnId = map.txnid
        this.discount = 'not available'
        this.fName = map.firstname
        this.email = map.email
        this.userCardNumber = map.cardnum
        this.mihpayid = map.mihpayid
        this.productinfo = map.productinfo
        this.merchantKey = map.key

    }


}

grails-app/domain/com/travelex/User/Role.groovy
package com.travelex.User

class Role {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

grails-app/domain/com/travelex/User/User.groovy
package com.travelex.User

import com.travelex.Hotel.BookingHistory
import com.travelex.flight.BookedFlight
import com.travelex.hotelFunctionality.TboHotelBookingVO
import com.travelex.social.SocialProfile
import org.apache.commons.lang.RandomStringUtils

import java.text.SimpleDateFormat

class User {

    transient springSecurityService

    Date dateCreated
    Date lastUpdated

    String firstName
    String lastName
    String username
    String password
    String mobNo
    String token = UUID.randomUUID().toString()
    String coustId
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    String pictureUrl
    String pictureName
    String pictureType
    Boolean hasVerifiedEmail = false
    String ipAddress

    List<SocialProfile> socialProfileList = []

    static constraints = {

        username blank: false, unique: true
        password blank: false
        ipAddress(blank: true, nullable: true)
        firstName(blank: true, nullable: true)
        lastName(blank: true, nullable: true)
        token(blank: true, nullable: true)
        pictureUrl(blank: true, nullable: true)
        mobNo(blank: true, nullable: true)
        pictureName(blank: true, nullable: true)
        pictureType(blank: true, nullable: true)
        coustId(nullable: false, blank: false)
    }

    static mapping = {
        password column: '`password`'
    }

    static hasMany = [socialProfileList: SocialProfile, bookingHistory: BookingHistory, bookedFlights: BookedFlight]

    Set<Role> getAuthorities() {
        UserRole.findAllByUser(this).collect { it.role } as Set
    }

    def beforeInsert() {
        encodePassword()
    }

    def beforeUpdate() {
        if (isDirty('password')) {
            encodePassword()
        }
    }

    protected void encodePassword() {
        password = springSecurityService.encodePassword(password)
    }


    void createOrCheckUserWhileBookHotel(TboHotelBookingVO tboHotelBookingVO) {
        this.firstName = tboHotelBookingVO.adult1MNameRoom1
        this.lastName = tboHotelBookingVO.adult1LNameRoom1
        this.username = tboHotelBookingVO.adult1EmailRoom1
        String randomAlphanumeric = RandomStringUtils.randomAlphanumeric(8)
        Date today = new Date()
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat('dd/MM/yyyy')
        String[] date = simpleDateFormat.format(today).split('/')
        this.coustId = "TR" + "CS" + randomAlphanumeric.toUpperCase() + "${date[0]}" + "${date[1]}" + "${date[2]}"
        this.accountExpired = false
        this.accountLocked = false
        this.hasVerifiedEmail = true
        this.passwordExpired = false
        this.enabled = true
        this.pictureName = "picNotAvailable"
        this.pictureType = "jpeg"
        if (!this.validate()) {
            this.errors.allErrors.each {
                log.info '--------error is--------' + it
            }
        }
    }


}

grails-app/domain/com/travelex/User/UserRole.groovy
package com.travelex.User

import org.apache.commons.lang.builder.HashCodeBuilder

class UserRole implements Serializable {

	User user
	Role role

	boolean equals(other) {
		if (!(other instanceof UserRole)) {
			return false
		}

		other.user?.id == user?.id &&
			other.role?.id == role?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (user) builder.append(user.id)
		if (role) builder.append(role.id)
		builder.toHashCode()
	}

	static UserRole get(long userId, long roleId) {
		find 'from UserRole where user.id=:userId and role.id=:roleId',
			[userId: userId, roleId: roleId]
	}

	static UserRole create(User user, Role role, boolean flush = false) {
		new UserRole(user: user, role: role).save(flush: flush, insert: true)
	}

	static boolean remove(User user, Role role, boolean flush = false) {
		UserRole instance = UserRole.findByUserAndRole(user, role)
		if (!instance) {
			return false
		}

		instance.delete(flush: flush)
		true
	}

	static void removeAll(User user) {
		executeUpdate 'DELETE FROM UserRole WHERE user=:user', [user: user]
	}

	static void removeAll(Role role) {
		executeUpdate 'DELETE FROM UserRole WHERE role=:role', [role: role]
	}

	static mapping = {
		id composite: ['role', 'user']
		version false
	}
}

grails-app/controllers/com/travelex/User/PaymentInfoController.groovy
package com.travelex.User


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PaymentInfoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond PaymentInfo.list(params), model: [paymentInfoInstanceCount: PaymentInfo.count()]
    }

    def show(PaymentInfo paymentInfoInstance) {
        respond paymentInfoInstance
    }

    @Transactional
    def update(PaymentInfo paymentInfoInstance) {
        if (paymentInfoInstance == null) {
            notFound()
            return
        }

        if (paymentInfoInstance.hasErrors()) {
            respond paymentInfoInstance.errors, view: 'edit'
            return
        }

        paymentInfoInstance.save flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'PaymentInfo.label', default: 'PaymentInfo'), paymentInfoInstance.id])
                redirect paymentInfoInstance
            }
            '*' { respond paymentInfoInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(PaymentInfo paymentInfoInstance) {

        if (paymentInfoInstance == null) {
            notFound()
            return
        }

        paymentInfoInstance.delete flush: true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'PaymentInfo.label', default: 'PaymentInfo'), paymentInfoInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'paymentInfoInstance.label', default: 'PaymentInfo'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/com/travelex/User/UserController.groovy
package com.travelex.User

import com.travelex.socials.login.SignUpCO
import grails.plugin.mail.MailService
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.web.multipart.commons.CommonsMultipartFile
import util.AppUtil

class UserController {
    def springSecurityService
    MailService mailService
    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [userList: User.list(params), userInstanceTotal: User.count()]
    }

    def create() {
//        [userInstance: new User(params)]
        render(view: '/user/create')
    }

    def save() {
        print('----------------------' + params)
        SignUpCO signUpCO = new SignUpCO()
        bindData(signUpCO, params)
        String tempRole = signUpCO.selectRole
        if (signUpCO.validate()) {
            print('11111111111111111111111')
            User userInstance = new User()
            userInstance = SignUpCO.createUserByAdmin(userInstance, signUpCO)
            if (userInstance.save(flush: true)) {
                String decideRole = signUpCO.selectRole
                Role role
                if (decideRole.equals("ROLE_ADMIN")) {
                    role = Role.findByAuthority("ROLE_ADMIN")
                    UserRole.create(userInstance, role, true)
                } else if (decideRole.equals("ROLE_PROVIDER")) {
                    role = Role.findByAuthority("ROLE_PROVIDER")
                    UserRole.create(userInstance, role, true)
                } else if (decideRole.equals("ROLE_USER")) {
                    role = Role.findByAuthority("ROLE_USER")
                    UserRole.create(userInstance, role, true)
                }
                flash.success = g.message(code: 'default.user.save.success.message')
                redirect(action: "show", id: userInstance?.id)
            } else {
                render(view: "create", model: [signUpCO: signUpCO, role: tempRole])
            }
        } else {
            render(view: "create", model: [signUpCO: signUpCO, role: tempRole])
        }
    }

    def show(Long id) {
        def userInstance = User.get(id)
        String role = UserRole.findByUser(userInstance).role.authority
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }
//        [userInstance: userInstance]
        render(view: '/user/show', model: [role: role, userInstance: userInstance])
    }

    def edit(Long id) {
        def userInstance = User.get(id)
        UserRole userRole = UserRole.findByUser(userInstance)
        String role = userRole.role.authority
        print('-------------------------' + role)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }
//        [userInstance: userInstance]
        render(view: '/user/edit', model: [role: role, userInstance: userInstance])
    }

    def update(Long id, Long version) {
        print('1111111111111111111111111' + params)
        SignUpCO signUpCO = new SignUpCO()
        bindData(signUpCO, params)
        User userInstance = User.get(id)
        print('222222222222222222222222222222' + userInstance)
        if (signUpCO.validate()) {
            print('333333333333333333333333333333')
            userInstance = SignUpCO.updateUserByAdmin(userInstance, signUpCO)
            if (!userInstance.save(flush: true)) {
                print('44444444444444444444444444444444444444')
                render(view: "edit", model: [userInstance: userInstance, signUpCO: signUpCO])
            } else {
                print('5555555555555555555555555555555')
                flash.message = message(code: 'default.updated.message', args: [message(code: 'user.label', default: 'User'), userInstance.id])
                redirect(action: "show", id: userInstance.id)
            }
        } else {
            print('666666666666666666666666666666666666')
            render(view: "edit", model: [userInstance: userInstance, signUpCO: signUpCO])
        }
    }

    def delete(Long id) {
        def userInstance = User.get(id)
        if (!userInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
            return
        }

        UserRole userRole = UserRole.findByUser(userInstance)
        print('--------------- user role is ------------------' + userRole)
        print('--------------- user role is ------------------' + userRole.user)
        print('--------------- user role is ------------------' + userRole.role)

        userRole.user = null;
        userRole.role = null;
//        userRole.delete(flush: true)
        print('--------------- user role is ------------------' + userRole.user)
        print('--------------- user role is ------------------' + userRole.role)
        try {
            userInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'user.label', default: 'User'), id])
            redirect(action: "show", id: id)
        }
    }

    def saveProfilePicture = {
        def webRootDir = AppUtil.staticResourcesDirPath
        print '---------------webRootDir-----------------------' + webRootDir
        CommonsMultipartFile uploadedFile = params.profilePicture
        print '---------------uploadedFile-----------------------' + uploadedFile
        if (uploadedFile?.bytes) {
            def user = springSecurityService.currentUser as User
            print '---------------11111111-----------------------'
            User userInstance = User.findById(user.id as Long)
            def userDir = new File(webRootDir, "/uploadedProfilePic/${userInstance.id}/")
            userDir.mkdirs()
            print '---------------222222222-----------------------'
            String fileName = uploadedFile.originalFilename.trim()
            uploadedFile.transferTo(new File(userDir, fileName))
            userInstance.pictureName = fileName
            userInstance.pictureType = uploadedFile.contentType
            userInstance.save(flush: true)
            redirect(controller: "home", action: "index")
        }
    }

    def showProfileImage = {
        def id = params.userId
        User buyerUser = User.findById(id as Long)
        def webRootDir = AppUtil.staticResourcesDirPath
        String imageName = buyerUser?.pictureName
        String fileNameToken = imageName?.tokenize('.')?.first()
        String fileExtension = imageName?.tokenize('.')?.last()
        def avatarFilePath
        try {
            avatarFilePath = new File(webRootDir, "/uploadedProfilePic/${buyerUser.id}/" + fileNameToken + ".${fileExtension}");
            log.info '---------avatarFilePath---------' + avatarFilePath.getAbsolutePath()
            if (avatarFilePath) {
                response.setContentType(buyerUser.pictureType)
                response.setContentLength(avatarFilePath?.size()?.toInteger())
                OutputStream out = response.getOutputStream();
                out.write(avatarFilePath.bytes);
                out.close();
            }

        } catch (Exception e) {
            log.info '---------Excepton----------------' + e.stackTrace
            e.printStackTrace()
        }
    }

    def sendMailToUser = {
        print('------------ params are ------------------' + params)
        try {
            print('1111111111111111111')
            mailService.sendMail {
                to params.receiver
                subject params.subject
                html params.body
            }
        }
        catch (Exception exc) {
            log.info('---------- exception occured while sending mail-------------------' + exc.printStackTrace())

        }
        flash.success = g.message(code: 'default.success.emailSend.message')
        redirect(controller: 'user', action: 'index')
    }


}

grails-app/views/user/_form.gsp
<%@ page import="com.travelex.User.User" %>

<div class="col-md-4">

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Username<travelx:star/></strong>
        </div>

        <div class="col-md-8">
            <g:textField class="form-control" name="username" value="${userInstance?.username}"/>
        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Password<travelx:star/></strong>
        </div>

        <div class="col-md-8">
            <input type="password" class="form-control" name="password"/>
        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong >Confirm Password<travelx:star/></strong>
        </div>

        <div class="col-md-8">
            <input type="password" class="form-control" name="confirmPassword"/>
        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>First Name<travelx:star/></strong>
        </div>

        <div class="col-md-8">
            <g:textField class="form-control" name="firstName" value="${userInstance?.firstName}"/>
        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Last Name<travelx:star/></strong>
        </div>

        <div class="col-md-8">
            <g:textField class="form-control" name="lastName" value="${userInstance?.lastName}"/>

        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Contact Number</strong>
        </div>

        <div class="col-md-8">
            <g:textField class="form-control" name="mobNo" value="${userInstance?.mobNo}"/>

        </div>
    </div>

    %{--<div class="fieldcontain ${hasErrors(bean: userInstance, field: 'socialProfileList', 'error')} ">--}%
    %{--<tr>--}%

    %{--<td>--}%
    %{--<label for="socialProfileList">--}%
    %{--<g:message code="user.socialProfileList.label" default="Social Profile List"/>--}%

    %{--</label>--}%
    %{--</td>--}%
    %{--<td>--}%

    %{--<ul class="one-to-many">--}%
    %{--<g:each in="${userInstance?.socialProfileList ?}" var="s">--}%
    %{--<li><g:link controller="socialProfile" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>--}%
    %{--</g:each>--}%
    %{--<li class="add">--}%
    %{--<g:link controller="socialProfile" action="create"--}%
    %{--params="['user.id': userInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'socialProfile.label', default: 'SocialProfile')])}</g:link>--}%
    %{--</li>--}%
    %{--</ul>--}%
    %{--</td>--}%
    %{--</tr>--}%

    %{--</div>--}%
</div>

<div class="col-md-4">

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Account Expired</strong>
        </div>

        <div class="col-md-8">
            <g:checkBox name="accountExpired" value="${userInstance?.accountExpired}"/>

        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Account Locked</strong>
        </div>

        <div class="col-md-8">
            <g:checkBox name="accountLocked" value="${userInstance?.accountLocked}"/>

        </div>
    </div>


    <div class="row" style="margin-top:2%">
        <div class="col-md-4">
            <strong>Has Verified Email</strong>
        </div>

        <div class="col-md-8">
            <g:checkBox name="hasVerifiedEmail" value="${userInstance?.hasVerifiedEmail}"/>

        </div>
    </div>


    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Password Expired</strong>
        </div>

        <div class="col-md-8">
            <g:checkBox name="passwordExpired" value="${userInstance?.passwordExpired}"/>

        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>Enabled</strong>
        </div>

        <div class="col-md-8">
            <g:checkBox name="enabled" value="${userInstance?.enabled}"/>

        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>ROLE_ADMIN</strong>
        </div>

        <div class="col-md-8">
            <g:radio name="selectRole" id="ROLE_ADMIN" value="ROLE_ADMIN"/>
        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>ROLE_USER</strong>
        </div>

        <div class="col-md-8">
            <g:radio name="selectRole" id="ROLE_USER" value="ROLE_USER"/>
        </div>
    </div>

    <div class="row" style="margin-top: 2%">
        <div class="col-md-4">
            <strong>ROLE_PROVIDER</strong>
        </div>

        <div class="col-md-8">
            <g:radio name="selectRole" id="ROLE_PROVIDER" value="ROLE_PROVIDER"/>
        </div>
    </div>

</div>

<div class="col-md-4"></div>
<script>
    $(document).ready(function () {
        if (${role=="ROLE_ADMIN"}) {
            $("#ROLE_ADMIN").attr('checked', true);
        }
        else if (${role=="ROLE_USER"}) {
            $("#ROLE_USER").attr('checked', true);
        }
        else if (${role=="ROLE_PROVIDER"}) {
            $("#ROLE_PROVIDER").attr('checked', true);
        }
    });
</script>

grails-app/views/user/_userTab.gsp
<ul class="nav nav-tabs">
    <li class="active"><a href="#list" data-toggle="tab">User List</a></li>
    <li><a href="#createNewUser" data-toggle="tab">Create New</a></li>
</ul>

grails-app/views/user/create.gsp
<%@ page import="com.travelex.User.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
</head>

<body>
<travelx:adminUserTab/>

            <div class="tab-content" style="margin-top: 1%;">

                <div class="tab-pane active" id="Users" style="margin-left: 5%">

                    <ul class="nav nav-tabs" >
                        <li><a href="${createLink(controller: 'user', action: 'index')}">User List</a></li>
                        <li class="active"><a href="${createLink(controller: 'user', action: 'create')}">Create New</a>
                        </li>
                    </ul>

                    <div class="tab-content" style="margin-top: 1%">
                        <div class="tab-pane active" id="editUser">
                            <div class="col-md-12">
                                <g:hasErrors bean="${signUpCO}">
                                    <div class="alert alert-danger alert-dismissible" role="alert">
                                        <button type="button" class="close" data-dismiss="alert"><span
                                                aria-hidden="true">&times;
                                        </span><span class="sr-only">Close</span></button>

                                        <div id="errors" class="alert alert-error">
                                            <g:renderErrors bean="${signUpCO}"/>
                                        </div>
                                    </div>
                                </g:hasErrors>
                                <g:form action="save">
                                    <fieldset class="form">
                                        <g:render template="form" model="[userInstance: signUpCO]"/>
                                    </fieldset>
                                    <fieldset class="buttons">
                                        <g:submitButton name="create" class="save btn btn-primary"
                                                        value="${message(code: 'default.button.create.label', default: 'Create')}"/>
                                    </fieldset>
                                </g:form>
                            </div>

                        </div>


                        <div class="tab-pane" id="createNewUser">
                            <p>Coming soon.</p>
                        </div>

                        <div class="tab-pane" id="tab3">
                            <p>Coming soon.</p>
                        </div>

                        <div class="tab-pane" id="tab4">
                            <p>Coming soon.</p>
                        </div>
                    </div>

                </div>


                <div class="tab-pane" id="Hotels">
                    <ul class="nav nav-tabs">
                        <li class="active"><a href="#hotelBookingList" data-toggle="tab">Booking List</a></li>
                        <li><a href="#hotelPaymentList" data-toggle="tab">Payment List</a></li>
                        <li><a href="#hotelCouponList" data-toggle="tab">Coupon List</a></li>
                        <li><a href="#hotelMarginList" data-toggle="tab">Margin List</a></li>

                    </ul>
                </div>

                <div class="tab-pane" id="Flights">
                    <h4>Coming soon !</h4>
                </div>

                <div class="tab-pane" id="Activity">
                    <h4>Coming soon !</h4>
                </div>

                <div class="tab-pane" id="serviceProvider">
                    <h4>Coming soon !</h4>
                </div>
            </div>
        %{--</div>--}%
    %{--</div>--}%
%{--</div>--}%
%{--<script>--}%
    %{--function activeButton(id) {--}%
        %{--$(".disableAll").removeClass('active')--}%
    %{--}--}%
%{--//</script>--}%

</body>
</html>

grails-app/views/user/index.gsp
<%@ page import="com.travelex.User.User" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin"/>
    <g:set var="entityName" value="${message(code: 'user.label', default: 'User')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="btn btn-toolbar">
    <a href="${createLink(controller: 'user', action: 'create')}" class="btn btn-primary">Create User</a>
</div>

<div id="list-user" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="username" title="${message(code: 'user.username.label', default: 'Username')}"/>

            <g:sortableColumn property="password" title="${message(code: 'user.password.label', default: 'Password')}"/>

            <g:sortableColumn property="ipAddress"
                              title="${message(code: 'user.ipAddress.label', default: 'Ip Address')}"/>

            <g:sortableColumn property="firstName"
                              title="${message(code: 'user.firstName.label', default: 'First Name')}"/>

            <g:sortableColumn property="lastName"
                              title="${message(code: 'user.lastName.label', default: 'Last Name')}"/>

            <g:sortableColumn property="token" title="${message(code: 'user.token.label', default: 'Token')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${userInstanceList}" status="i" var="userInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${userInstance?.id}">${fieldValue(bean: userInstance, field: "username")}</g:link></td>

                <td>${fieldValue(bean: userInstance, field: "password")}</td>

                <td>${fieldValue(bean: userInstance, field: "ipAddress")}</td>

                <td>${fieldValue(bean: userInstance, field: "firstName")}</td>

                <td>${fieldValue(bean: userInstance, field: "lastName")}</td>

                <td>${fieldValue(bean: userInstance, field: "token")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${userInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>